# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fQbTGKR99MSZLDRdIsNEzgfZBB1xCA5W

zad 1
"""

def wiadomość (Name, Surname):
    return f'Cześć {Name} {Surname}!'

Name = input("Podaj imię: ")
Surname = input("Podaj nazwisko: ")
wynik = wiadomość(Name, Surname)
print(wynik)

"""zad 2"""

def pomnoz(a, b):
    wynik = a * b
    return wynik

liczba1 = int(input("Podaj pierwszą liczbę całkowitą: "))
liczba2 = int(input("Podaj drugą liczbę całkowitą: "))

wynik_mnozenia = pomnoz(liczba1, liczba2)
print("Wynik mnożenia:", wynik_mnozenia)

"""zad 3"""

def rezultat(liczba):
    return liczba % 2 == 0

liczba = int(input("Podaj liczbę całkowitą: "))
rezulatat1 = rezultat(liczba)

if rezultat:
    print("To jest liczba parzysta!")
else:
    print("To jest liczba nieparzysta!")

"""zad 4"""

def sprawdz_suma(a, b, c):
    suma_ab = a + b
    return suma_ab >= c

# Pobieranie liczb
liczba1 = int(input("Podaj pierwszą liczbę całkowitą: "))
liczba2 = int(input("Podaj drugą liczbę całkowitą: "))
liczba3 = int(input("Podaj trzecią liczbę całkowitą: "))

wynik = sprawdz_suma(liczba1, liczba2, liczba3)
print("Czy suma pierwszych dwóch liczb jest większa lub równa trzeciej?", wynik)

"""zad 5"""

def wartość(input_list, value):
    return value in input_list

lista = [1, 2, 3, 4, 5]

sprawdz = int(input("Podaj wartość do sprawdzenia: "))
wynik = wartość(lista, sprawdz)
print("Czy ten wynik jest w liście? :", wynik)

"""zad 6"""

def process_lists(list1, list2):
    combined_list = list1 + list2
    unique_list = list(set(combined_list))
    powered_list = [x**3 for x in unique_list]

    return powered_list

list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]
result = process_lists(list1, list2)
print("Final list:", result)